#
# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2020-2024 Lune Reseau, Inc.
#

lib_sources = files('arrlist.c',
    'conv.c',
    'csum.c',
    'htable.c',
    'idlist.c',
    'idtable.c',
    'init.c',
    'msgqueue.c',
    'ringbuf.c',
    'tiny_idtable.c',
    'utils.c')

sources += lib_sources
